from marquetry.functions.loss.classification.classification_cross_entropy import classification_cross_entropy
from marquetry.functions.loss.classification.sigmoid_cross_entropy import sigmoid_cross_entropy
from marquetry.functions.loss.classification.sigmoid_cross_entropy import SigmoidCrossEntropy
from marquetry.functions.loss.classification.softmax_cross_entropy import softmax_cross_entropy
from marquetry.functions.loss.classification.softmax_cross_entropy import SoftmaxCrossEntropy

from marquetry.functions.loss.regression.mean_absolute_error import mean_absolute_error
from marquetry.functions.loss.regression.mean_absolute_error import MeanAbsoluteError
from marquetry.functions.loss.regression.mean_squared_error import mean_squared_error
from marquetry.functions.loss.regression.mean_squared_error import MeanSquaredError
